name: elearn
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  objectdb: ^1.0.7+1
  curved_navigation_bar: ^0.3.7
  flutter_svg: ^0.20.0-nullsafety.3
  speech_to_text: ^3.1.0
  permission_handler: ^4.2.0+hotfix.1
  radial_button: ^1.0.0
  http: ^0.13.3
  fluttertoast: ^8.0.6
  flutter_switch: ^0.3.1
  hive: ^2.0.4
  path_provider: ^1.6.27
  path: ^1.8.0
  dio: ^4.0.0
  provider: ^5.0.0
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.5.0
  shimmer: ^2.0.0
  shared_preferences: ^0.5.12+4
  percent_indicator: ^3.0.1
  downloads_path_provider: ^0.1.0
  flutter_downloader: ^1.5.2
  flutter_share: ^2.0.0
  awesome_dialog: ^2.0.0
  webview_flutter: ^1.0.7
  sqflite: ^2.0.0+3
  firebase_core: ^0.8.0-nullsafety.1
  file_picker: ^2.1.6
  modal_bottom_sheet: ^2.0.0
  rflutter_alert: ^2.0.2
  firebase_auth: ^0.21.0-nullsafety.0
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  onesignal_flutter: 3.2.0
  admob_flutter: ^1.0.1
  flutter_cached_pdfview: ^0.3.5
  flutter_pdfview: ^1.0.4
  change_app_package_name: ^1.0.0
  flutter_html: any
  intl: ^0.17.0-nullsafety.2
  equatable: ^2.0.0
  readmore: ^2.1.0
  url_launcher: ^6.0.5
  get: ^4.1.4
  image_picker:
  epub_viewer: ^0.1.8
  lazy_load_scrollview: ^1.3.0
  flutter_rating_bar: ^4.0.0
  exif: ^3.0.0
  apple_sign_in: ^0.1.0
  splashscreen: ^1.3.5
  flutter_localizations:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flag/
    - assets/
    - assets/fonts/
    - assets/epub/
    - assets/listview/

  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          style: italic
#    - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
  enabled: true
